<?php
/**
 * Per-product "Exclude from llms.txt" checkbox. Stored as post meta
 * `_lltxt_exclude` = '1'; consumed by Lltxt_Catalog_Reader's meta_query so the
 * product is dropped from every AI-discovery file at the source.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * @package LLMsTxtForWooCommerce
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class Lltxt_Product_Metabox.
 */
class Lltxt_Product_Metabox {

	const META_KEY  = '_lltxt_exclude';
	const NONCE_KEY = 'lltxt_product_metabox_nonce';

	/**
	 * Register hooks.
	 *
	 * @return void
	 */
	public static function init() {
		add_action( 'add_meta_boxes', array( __CLASS__, 'register' ) );
		add_action( 'save_post_product', array( __CLASS__, 'save' ), 10, 2 );
	}

	/**
	 * Register the metabox on the product post type.
	 *
	 * @return void
	 */
	public static function register() {
		add_meta_box(
			'lltxt_product_exclude',
			__( 'LLMs.txt for AI Shoppers', 'agentic-commerce-llms-txt' ),
			array( __CLASS__, 'render' ),
			'product',
			'side',
			'low'
		);
	}

	/**
	 * Render the metabox body.
	 *
	 * @param WP_Post $post Current post.
	 * @return void
	 */
	public static function render( $post ) {
		wp_nonce_field( self::NONCE_KEY, self::NONCE_KEY );
		$checked = '1' === (string) get_post_meta( $post->ID, self::META_KEY, true );
		?>
		<label for="lltxt_exclude">
			<input type="checkbox" id="lltxt_exclude" name="lltxt_exclude" value="1" <?php checked( true, $checked ); ?> />
			<?php esc_html_e( 'Exclude this product from AI discovery', 'agentic-commerce-llms-txt' ); ?>
		</label>
		<p class="description">
			<?php esc_html_e( 'When checked, this product is removed from llms.txt, catalog.json, sitemap-ai.xml, and the other AI-discovery files generated by the plugin.', 'agentic-commerce-llms-txt' ); ?>
		</p>
		<?php
	}

	/**
	 * Persist the checkbox value with nonce + capability + sanitize.
	 *
	 * @param int     $post_id Post ID.
	 * @param WP_Post $post    Post object.
	 * @return void
	 */
	public static function save( $post_id, $post ) {
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return;
		}
		if ( ! isset( $_POST[ self::NONCE_KEY ] ) ) {
			return;
		}
		$nonce = sanitize_text_field( wp_unslash( $_POST[ self::NONCE_KEY ] ) );
		if ( ! wp_verify_nonce( $nonce, self::NONCE_KEY ) ) {
			return;
		}
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}
		$raw   = isset( $_POST['lltxt_exclude'] ) ? sanitize_text_field( wp_unslash( $_POST['lltxt_exclude'] ) ) : '';
		$value = ( '1' === $raw ) ? '1' : '0';
		update_post_meta( $post_id, self::META_KEY, $value );
	}
}
