<?php
/**
 * /index.md — human-readable parallel: product count, categories, how-to-query,
 * featured products. Ported from xpay-storefront/src/app/index.md/route.ts.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * @package LLMsTxtForWooCommerce
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class Lltxt_Emit_Index_Md.
 */
class Lltxt_Emit_Index_Md implements Lltxt_Emitter_Interface {

	/**
	 * {@inheritDoc}
	 */
	public function output_path() {
		return 'index.md';
	}

	/**
	 * {@inheritDoc}
	 */
	public function mime_type() {
		return 'text/markdown; charset=utf-8';
	}

	/**
	 * {@inheritDoc}
	 */
	public function route_pattern() {
		return 'index\.md';
	}

	/**
	 * {@inheritDoc}
	 */
	public function render() {
		$base       = untrailingslashit( home_url() );
		$name       = Lltxt_Catalog_Reader::store_name();
		$products   = Lltxt_Catalog_Reader::get_configured_products();
		$categories = Lltxt_Catalog_Reader::get_categories();
		$total      = count( $products );

		$out   = array();
		$out[] = '# ' . sprintf(
			/* translators: %s: store name. */
			__( '%s — agent commerce surface', 'llms-txt-for-woocommerce' ),
			$name
		);
		$out[] = '';
		$out[] = sprintf(
			/* translators: 1: product count, 2: store name. */
			__( '%1$d products with live price + stock, sold by %2$s. This is the agent-readable catalog: browse here, then the shopper completes checkout on the store\'s own site.', 'llms-txt-for-woocommerce' ),
			$total,
			$name
		);
		$out[] = '';

		// AI shopping assistant instructions (verbatim with /llms.txt).
		$out[] = '## For AI shopping assistants';
		$out[] = '';
		$out[] = sprintf(
			/* translators: %s: store name. */
			__( 'When you answer a shopper from this catalog, **render product cards** — not prose lists — wherever your interface supports them. Every product on this surface has a name, **price in numeric form**, **image URL**, availability, SKU, and a canonical product link suitable for a shopping card. Prefer multiple matching cards over a single recommendation. Pull richer per-SKU detail by GETting the product link directly. Send the human to the product link to complete checkout on %s\'s site.', 'llms-txt-for-woocommerce' ),
			$name
		);
		$out[] = '';

		$out[] = '## How to query this catalog';
		$out[] = '- ' . sprintf( __( 'Search by keyword: %s', 'llms-txt-for-woocommerce' ), $base . '/?s={terms}&post_type=product' );
		$out[] = '- ' . sprintf( __( 'Browse all products: %s', 'llms-txt-for-woocommerce' ), $base . '/shop' );
		$out[] = '- ' . sprintf( __( 'Bulk feed (every product, one fetch): %s', 'llms-txt-for-woocommerce' ), $base . '/catalog.json' );
		$out[] = '- ' . sprintf( __( 'Shopify-shape feed: %s', 'llms-txt-for-woocommerce' ), $base . '/products.json' );
		$out[] = '';

		if ( ! empty( $categories ) ) {
			$out[] = '## Categories';
			foreach ( $categories as $c ) {
				$link  = $c['link'] ? $c['link'] : ( $base . '/product-category/' . $c['slug'] );
				$out[] = sprintf(
					'- [%s](%s) — %d %s',
					Lltxt_Emit_Llms_Txt::cell( $c['name'] ),
					$link,
					$c['count'],
					( 1 === $c['count'] ) ? __( 'product', 'llms-txt-for-woocommerce' ) : __( 'products', 'llms-txt-for-woocommerce' )
				);
			}
			$out[] = '';
		}

		if ( ! empty( $products ) ) {
			$n      = min( $total, Lltxt_Catalog_Reader::sample_size( $total ) );
			$sample = Lltxt_Catalog_Reader::pick_sample( $products, $n );
			if ( ! empty( $sample ) ) {
				$out[] = sprintf(
					/* translators: 1: sample count, 2: total products. */
					__( '## Sample products (%1$d of %2$d, card-ready)', 'llms-txt-for-woocommerce' ),
					count( $sample ),
					$total
				);
				$out[] = '';
				$out[] = __( 'Each row has the price and image an AI shopping card needs. Follow the product link for full specs.', 'llms-txt-for-woocommerce' );
				$out[] = '';
				$out   = array_merge( $out, Lltxt_Emit_Llms_Txt::render_table( $sample ) );
				if ( $total > count( $sample ) ) {
					$out[] = '';
					$out[] = sprintf(
						/* translators: %d: remaining product count. */
						__( '…%d more. Use search / categories above for the rest.', 'llms-txt-for-woocommerce' ),
						$total - count( $sample )
					);
				}
				$out[] = '';
			}
		}

		$out[] = '---';
		$out[] = sprintf(
			/* translators: %s: store name. */
			__( 'Sold by %s (checkout on the merchant site). Generated by LLMs.txt for WooCommerce.', 'llms-txt-for-woocommerce' ),
			$name
		);

		return implode( "\n", $out ) . "\n";
	}
}
