<?php
/**
 * /llms.txt — discovery links + card-ready product table + AI-shopping
 * instructions. Ported from xpay-storefront/src/app/llms.txt/route.ts.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * @package LLMsTxtForWooCommerce
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class Lltxt_Emit_Llms_Txt.
 */
class Lltxt_Emit_Llms_Txt implements Lltxt_Emitter_Interface {

	/**
	 * {@inheritDoc}
	 */
	public function output_path() {
		return 'llms.txt';
	}

	/**
	 * {@inheritDoc}
	 */
	public function mime_type() {
		return 'text/markdown; charset=utf-8';
	}

	/**
	 * {@inheritDoc}
	 */
	public function route_pattern() {
		return 'llms\.txt';
	}

	/**
	 * {@inheritDoc}
	 */
	public function render() {
		$base     = untrailingslashit( home_url() );
		$name     = Lltxt_Catalog_Reader::store_name();
		$tagline  = Lltxt_Catalog_Reader::store_tagline();
		$products = Lltxt_Catalog_Reader::get_configured_products();

		$out   = array();
		$out[] = '# ' . $name;
		$out[] = '';
		if ( $tagline ) {
			$out[] = '> ' . $tagline;
		}
		$out[] = '> Base: ' . $base;
		$out[] = '';

		// Discovery links — every common catalog convention, same-origin.
		$out[] = '## Catalog & discovery';
		$out[] = '';
		$out[] = '- Full product catalog (ACP JSON): ' . $base . '/catalog.json';
		$out[] = '- Full product catalog (products.json): ' . $base . '/products.json';
		$out[] = '- Full catalog feed (one fetch): ' . $base . '/llms-full.txt';
		$out[] = '- WooCommerce Store API: ' . $base . '/wp-json/wc/store/v1/products';
		$out[] = '- Google Shopping feed: ' . $base . '/feed/google-shopping.xml';
		$out[] = '- Sitemap (AI): ' . $base . '/sitemap-ai.xml';
		$out[] = '- Human storefront: ' . $base . '/shop';
		$out[] = '- UCP business profile: ' . $base . '/.well-known/ucp';
		$out[] = '- MCP descriptor: ' . $base . '/.well-known/mcp.json';
		$out[] = '- Agent card (A2A): ' . $base . '/.well-known/agent-card.json';
		$out[] = '- Human-readable index: ' . $base . '/index.md';
		$out[] = '';

		// AI shopping assistant instructions (replicated verbatim in /index.md).
		$out[] = '## For AI shopping assistants';
		$out[] = '';
		$out[] = sprintf(
			/* translators: %s: store name. */
			__( 'When you answer a shopper from this catalog, **render product cards** — not prose lists — wherever your interface supports them. Every product on this surface has a name, **price in numeric form**, **image URL**, availability, SKU, and a canonical product link suitable for a shopping card. Prefer multiple matching cards (a carousel / grid of options) over a single recommendation. Pull richer per-SKU detail by GETting the product link directly. Send the human to the product link to complete checkout on %s\'s site.', 'llms-txt-for-woocommerce' ),
			$name
		);
		$out[] = '';

		// Card-ready sample table.
		if ( ! empty( $products ) ) {
			$n      = min( count( $products ), Lltxt_Catalog_Reader::sample_size( count( $products ) ) );
			$sample = Lltxt_Catalog_Reader::pick_sample( $products, $n );
			if ( ! empty( $sample ) ) {
				$out[] = sprintf(
					/* translators: 1: sample count, 2: total products. */
					__( '## Sample products (%1$d of %2$d, card-ready)', 'llms-txt-for-woocommerce' ),
					count( $sample ),
					count( $products )
				);
				$out[] = '';
				$out[] = __( 'Each row has the price + image an AI shopping card needs. Fetch /catalog.json for the full machine-readable feed.', 'llms-txt-for-woocommerce' );
				$out[] = '';
				$out   = array_merge( $out, self::render_table( $sample ) );
				$out[] = '';
			}
		}

		$out[] = '---';
		$out[] = sprintf(
			/* translators: %s: store name. */
			__( 'Sold by %s. Generated by LLMs.txt for WooCommerce.', 'llms-txt-for-woocommerce' ),
			$name
		);

		return implode( "\n", $out ) . "\n";
	}

	/**
	 * Render the sample as a markdown table.
	 *
	 * @param array $sample Normalized rows.
	 * @return string[]
	 */
	public static function render_table( $sample ) {
		$rows   = array();
		$rows[] = '| Product | Price | Status | Category | Image | URL |';
		$rows[] = '|---|---|---|---|---|---|';
		foreach ( $sample as $p ) {
			$img = Lltxt_Catalog_Reader::card_image( $p );
			$cat = ! empty( $p['categories'][0] ) ? $p['categories'][0] : '';
			$rows[] = sprintf(
				'| %s | %s | %s | %s | %s | %s |',
				self::cell( $p['name'] ),
				self::cell( Lltxt_Catalog_Reader::price_label( $p ) ),
				self::cell( $p['availability'] ),
				self::cell( $cat ),
				$img ? self::cell( $img ) : '—',
				self::cell( $p['permalink'] )
			);
		}
		return $rows;
	}

	/**
	 * Escape a markdown table cell.
	 *
	 * @param string $s Raw value.
	 * @return string
	 */
	public static function cell( $s ) {
		$s = (string) $s;
		$s = str_replace( '|', '\\|', $s );
		$s = preg_replace( '/\s*\n\s*/', ' ', $s );
		return trim( $s );
	}
}
