<?php
/**
 * /llms-full.txt — full catalog dump, one product per markdown section, for
 * LLMs that want everything in a single fetch. Fresh design (no TS source).
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * @package LLMsTxtForWooCommerce
 */

defined( 'ABSPATH' ) || exit;

/**
 * Class Lltxt_Emit_Llms_Full_Txt.
 */
class Lltxt_Emit_Llms_Full_Txt implements Lltxt_Emitter_Interface {

	/**
	 * {@inheritDoc}
	 */
	public function output_path() {
		return 'llms-full.txt';
	}

	/**
	 * {@inheritDoc}
	 */
	public function mime_type() {
		return 'text/markdown; charset=utf-8';
	}

	/**
	 * {@inheritDoc}
	 */
	public function route_pattern() {
		return 'llms\-full\.txt';
	}

	/**
	 * {@inheritDoc}
	 */
	public function render() {
		$base = untrailingslashit( home_url() );
		$name = Lltxt_Catalog_Reader::store_name();

		// Full catalog dump — read up to a sane ceiling so we don't OOM on huge stores.
		$products = Lltxt_Catalog_Reader::get_products(
			array(
				'limit'   => 5000,
				'orderby' => 'total_sales',
				'order'   => 'DESC',
			)
		);

		$out   = array();
		$out[] = '# ' . sprintf(
			/* translators: %s: store name. */
			__( '%s — full catalog', 'llms-txt-for-woocommerce' ),
			$name
		);
		$out[] = '';
		$out[] = sprintf(
			/* translators: %d: product count. */
			__( 'Complete machine-readable catalog (%d products). One section per product.', 'llms-txt-for-woocommerce' ),
			count( $products )
		);
		$out[] = '';

		foreach ( $products as $p ) {
			$out[] = '## ' . $p['name'];
			$out[] = '';
			$price = Lltxt_Catalog_Reader::price_label( $p );
			if ( '' !== $price ) {
				$out[] = '- ' . __( 'Price', 'llms-txt-for-woocommerce' ) . ': ' . $price . ' ' . $p['currency'];
			}
			if ( $p['on_sale'] && '' !== $p['regular_price'] ) {
				$out[] = '- ' . __( 'Regular price', 'llms-txt-for-woocommerce' ) . ': ' . Lltxt_Catalog_Reader::format_price( $p['regular_price'] );
			}
			if ( '' !== $p['sku'] ) {
				$out[] = '- ' . __( 'SKU', 'llms-txt-for-woocommerce' ) . ': ' . $p['sku'];
			}
			$out[] = '- ' . __( 'Availability', 'llms-txt-for-woocommerce' ) . ': ' . $p['availability'];
			if ( ! empty( $p['categories'] ) ) {
				$out[] = '- ' . __( 'Categories', 'llms-txt-for-woocommerce' ) . ': ' . implode( ', ', $p['categories'] );
			}
			$img = Lltxt_Catalog_Reader::card_image( $p );
			if ( $img ) {
				$out[] = '- ' . __( 'Image', 'llms-txt-for-woocommerce' ) . ': ' . $img;
			}
			$out[] = '- ' . __( 'URL', 'llms-txt-for-woocommerce' ) . ': ' . $p['permalink'];
			$desc  = $p['short_description'] ? $p['short_description'] : $p['description'];
			if ( $desc ) {
				$out[] = '';
				$out[] = wp_trim_words( $desc, 120, '…' );
			}
			$out[] = '';
		}

		$out[] = '---';
		$out[] = sprintf(
			/* translators: %s: base URL. */
			__( 'Source: %s · Generated by LLMs.txt for WooCommerce.', 'llms-txt-for-woocommerce' ),
			$base
		);

		return implode( "\n", $out ) . "\n";
	}
}
